# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-09 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('firstname', models.TextField(max_length=20)),
                ('lastname', models.TextField(max_length=20)),
                ('gender', models.TextField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6)),
            ],
        ),
    ]
